import Foundation
import AppKit

@MainActor
final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [ClipItem] = []
    @Published var searchText: String = ""
    @Published private(set) var secretsSkippedThisSession: Int = 0
    @Published var transformError: String?
    @Published private(set) var settings: AppSettings

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let storageURL: URL
    private let imagesDirectory: URL
    private let fileManager: FileManager

    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    var filteredItems: [ClipItem] {
        guard !searchText.isEmpty else { return items }
        let q = searchText
        return items.filter { item in
            switch item.kind {
            case .text:
                return item.content.localizedCaseInsensitiveContains(q)
                    || (item.sourceApp?.localizedCaseInsensitiveContains(q) ?? false)
            case .image:
                return "image".localizedCaseInsensitiveContains(q)
                    || (item.sourceApp?.localizedCaseInsensitiveContains(q) ?? false)
            }
        }
    }

    var unpinnedCount: Int {
        items.filter { !$0.isPinned }.count
    }

    /// Production store under Application Support/Clipper.
    convenience init(settings: AppSettings = .shared) {
        let fm = FileManager.default
        let appSupport = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let dir = appSupport.appendingPathComponent("Clipper", isDirectory: true)
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        let images = dir.appendingPathComponent("images", isDirectory: true)
        try? fm.createDirectory(at: images, withIntermediateDirectories: true)
        self.init(
            settings: settings,
            storageURL: dir.appendingPathComponent("history.json"),
            imagesDirectory: images,
            fileManager: fm
        )
    }

    /// Injectable paths for tests / previews.
    init(
        settings: AppSettings,
        storageURL: URL,
        imagesDirectory: URL,
        fileManager: FileManager = .default
    ) {
        self.settings = settings
        self.storageURL = storageURL
        self.imagesDirectory = imagesDirectory
        self.fileManager = fileManager
        self.lastChangeCount = NSPasteboard.general.changeCount
        try? fileManager.createDirectory(at: imagesDirectory, withIntermediateDirectories: true)
        load()
    }

    func startMonitoring() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.checkPasteboard()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - Pasteboard

    private func checkPasteboard() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let concealed = pasteboardIsSensitive()
        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            handleTextCapture(string, sourceApp: source, sensitivePasteboard: concealed)
            return
        }

        if !concealed, let image = readImageFromPasteboard() {
            handleImageCapture(image, sourceApp: source)
        }
    }

    private func pasteboardIsSensitive() -> Bool {
        let types = pasteboard.types ?? []
        return types.contains(Self.concealedType)
            || types.contains(Self.transientType)
            || types.contains(Self.autoGeneratedType)
    }

    private func handleTextCapture(_ string: String, sourceApp: String?, sensitivePasteboard: Bool) {
        let decision = HistoryPolicy.decision(
            text: string,
            sourceBundleId: sourceApp,
            ignoredBundleIds: settings.ignoredBundleIds,
            secretMode: settings.secretMode,
            pasteboardIsConcealedOrTransient: sensitivePasteboard
        )

        switch decision {
        case .skip(let reason):
            if reason == "secret" || reason == "concealed_or_transient" {
                secretsSkippedThisSession += 1
            }
            return
        case .capture(let text, let redacted):
            addTextItem(content: text, sourceApp: sourceApp, redacted: redacted)
        }
    }

    private func handleImageCapture(_ image: NSImage, sourceApp: String?) {
        if let bundle = sourceApp, settings.ignoredBundleIds.contains(bundle) {
            return
        }
        // Skip duplicate of most recent image by change is enough; still avoid empty
        guard let filename = saveImage(image) else { return }
        let item = ClipItem(
            kind: .image,
            content: filename,
            sourceApp: sourceApp,
            redacted: false
        )
        insert(item)
    }

    private func addTextItem(content: String, sourceApp: String?, redacted: Bool) {
        if let first = items.first,
           first.kind == .text,
           first.content == content {
            return
        }
        let item = ClipItem(
            kind: .text,
            content: content,
            sourceApp: sourceApp,
            redacted: redacted
        )
        insert(item)
    }

    private func insert(_ item: ClipItem) {
        var next = items
        // Drop files for items that will be trimmed away
        let beforeIds = Set(items.map(\.id))
        next.insert(item, at: 0)
        next = next.clippedToHistoryLimit(settings.historyLimit)
        let afterIds = Set(next.map(\.id))
        let removed = beforeIds.subtracting(afterIds)
        for old in items where removed.contains(old.id) {
            deleteImageFileIfNeeded(old)
        }
        items = next
        save()
    }

    // MARK: - Actions

    func recopy(_ item: ClipItem) {
        transformError = nil
        pasteboard.clearContents()
        switch item.kind {
        case .text:
            pasteboard.setString(item.content, forType: .string)
        case .image:
            let url = imagesDirectory.appendingPathComponent(item.content)
            if let data = try? Data(contentsOf: url),
               let image = NSImage(data: data) {
                pasteboard.writeObjects([image])
            } else if let tiff = NSImage(contentsOf: url)?.tiffRepresentation {
                pasteboard.setData(tiff, forType: .tiff)
            }
        }
        lastChangeCount = pasteboard.changeCount
    }

    func togglePin(_ item: ClipItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        save()
    }

    func delete(_ item: ClipItem) {
        deleteImageFileIfNeeded(item)
        items.removeAll { $0.id == item.id }
        save()
    }

    func clearUnpinned() {
        let removed = items.filter { !$0.isPinned }
        for item in removed {
            deleteImageFileIfNeeded(item)
        }
        items.removeAll { !$0.isPinned }
        save()
    }

    /// Apply a transform to a text clip: put result on the pasteboard and insert a new history item.
    func transform(_ item: ClipItem, using rule: ClipTransform) {
        transformError = nil
        guard item.kind == .text else {
            transformError = ClipTransformError.notText.errorDescription
            return
        }
        do {
            let output = try ClipTransforms.apply(rule, to: item.content)
            pasteboard.clearContents()
            pasteboard.setString(output, forType: .string)
            lastChangeCount = pasteboard.changeCount
            addTextItem(content: output, sourceApp: item.sourceApp, redacted: false)
        } catch {
            transformError = (error as? LocalizedError)?.errorDescription
                ?? error.localizedDescription
        }
    }

    func clearTransformError() {
        transformError = nil
    }

    func imageURL(for item: ClipItem) -> URL? {
        guard item.kind == .image else { return nil }
        return imagesDirectory.appendingPathComponent(item.content)
    }

    func loadThumbnail(for item: ClipItem, maxSide: CGFloat = 64) -> NSImage? {
        guard let url = imageURL(for: item),
              let image = NSImage(contentsOf: url) else { return nil }
        return downscale(image, maxSide: maxSide)
    }

    // MARK: - Images

    private func readImageFromPasteboard() -> NSImage? {
        if let data = pasteboard.data(forType: .png), let image = NSImage(data: data) {
            return image
        }
        if let data = pasteboard.data(forType: .tiff), let image = NSImage(data: data) {
            return image
        }
        return nil
    }

    private func saveImage(_ image: NSImage) -> String? {
        let scaled = downscale(image, maxSide: 1600)
        guard let tiff = scaled.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:]) else { return nil }
        let name = "\(UUID().uuidString).png"
        let url = imagesDirectory.appendingPathComponent(name)
        do {
            try png.write(to: url)
            return name
        } catch {
            return nil
        }
    }

    private func downscale(_ image: NSImage, maxSide: CGFloat) -> NSImage {
        let size = image.size
        let longest = max(size.width, size.height)
        guard longest > maxSide, longest > 0 else { return image }
        let scale = maxSide / longest
        let newSize = NSSize(width: size.width * scale, height: size.height * scale)
        let out = NSImage(size: newSize)
        out.lockFocus()
        image.draw(
            in: NSRect(origin: .zero, size: newSize),
            from: NSRect(origin: .zero, size: size),
            operation: .copy,
            fraction: 1.0
        )
        out.unlockFocus()
        return out
    }

    private func deleteImageFileIfNeeded(_ item: ClipItem) {
        guard item.kind == .image else { return }
        let url = imagesDirectory.appendingPathComponent(item.content)
        try? fileManager.removeItem(at: url)
    }

    // MARK: - Persistence

    private func load() {
        guard let data = try? Data(contentsOf: storageURL) else { return }
        do {
            let decoded = try JSONDecoder().decode([ClipItem].self, from: data)
            items = decoded
        } catch {
            // Corrupt JSON → start empty, do not crash
            items = []
        }
    }

    private func save() {
        do {
            let data = try JSONEncoder().encode(items)
            try data.write(to: storageURL, options: [.atomic])
        } catch {
            // Keep in-memory; silent-safe
        }
    }
}
