#!/usr/bin/env bash
set -euo pipefail

VERSION="${1:-0.2.0}"
SIGN_IDENTITY="${2:-}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$ROOT/.build/release"
APP_DIR="$ROOT/Clipper.app"
KS_UTIL="$ROOT/.build/checkouts/KeyboardShortcuts/Sources/KeyboardShortcuts/Utilities.swift"

patch_keyboard_shortcuts() {
  # SwiftPM's generated Bundle.module fatalErrors unless
  # KeyboardShortcuts_KeyboardShortcuts.bundle sits at the .app root.
  # That layout fails codesign ("unsealed contents present in the bundle root").
  # Rewrite localization to look in Contents/Resources instead.
  if [[ ! -f "$KS_UTIL" ]]; then
    echo "error: KeyboardShortcuts checkout missing at $KS_UTIL" >&2
    exit 1
  fi
  if grep -q "keyboardShortcutsSafeBundle" "$KS_UTIL"; then
    return 0
  fi
  chmod +w "$KS_UTIL"
  python3 - "$KS_UTIL" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text()
if "keyboardShortcutsSafeBundle" in text:
    sys.exit(0)

old = "NSLocalizedString(self, bundle: .module, comment: self)"
new = "NSLocalizedString(self, bundle: .keyboardShortcutsSafeBundle, comment: self)"
if old not in text:
    raise SystemExit("KeyboardShortcuts Utilities.swift no longer uses Bundle.module; update the patch")
text = text.replace(old, new, 1)

text += """

private extension Bundle {
    /// Avoids the autogenerated `Bundle.module` trap when the resource bundle
    /// lives in Contents/Resources (the codesign-valid location).
    static let keyboardShortcutsSafeBundle: Bundle = {
        if let url = Bundle.main.url(forResource: "KeyboardShortcuts_KeyboardShortcuts", withExtension: "bundle"),
           let bundle = Bundle(url: url) {
            return bundle
        }
        let rootURL = Bundle.main.bundleURL.appendingPathComponent("KeyboardShortcuts_KeyboardShortcuts.bundle")
        if let bundle = Bundle(url: rootURL) {
            return bundle
        }
        return Bundle.main
    }()
}
"""
path.write_text(text)
PY
}

echo "==> Resolving packages"
swift package resolve --package-path "$ROOT"

echo "==> Patching KeyboardShortcuts resource lookup"
patch_keyboard_shortcuts

echo "==> Building release binary"
swift build -c release --package-path "$ROOT"

if ! grep -q "keyboardShortcutsSafeBundle" "$KS_UTIL"; then
  echo "==> SwiftPM reset KeyboardShortcuts; re-applying patch and rebuilding"
  patch_keyboard_shortcuts
  swift build -c release --package-path "$ROOT"
fi
if ! grep -q "keyboardShortcutsSafeBundle" "$KS_UTIL"; then
  echo "error: KeyboardShortcuts patch did not stick through the build" >&2
  exit 1
fi

echo "==> Creating app bundle"
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/"{MacOS,Resources}

cp "$BUILD_DIR/Clipper" "$APP_DIR/Contents/MacOS/Clipper"
chmod +x "$APP_DIR/Contents/MacOS/Clipper"

# SF Symbol → icns via `swift -` JIT is unreliable (AppKit symbols missing).
# Prefer a prebuilt icns if present; otherwise ship without a custom icon.
if [[ -f "$ROOT/Sources/Clipper/Clipper.icns" ]]; then
  cp "$ROOT/Sources/Clipper/Clipper.icns" "$APP_DIR/Contents/Resources/Clipper.icns"
  echo "Using Sources/Clipper/Clipper.icns"
else
  echo "Skipping custom icon (no Clipper.icns; menu bar uses SF Symbol at runtime)"
fi

cp "$ROOT/Sources/Clipper/Info.plist" "$APP_DIR/Contents/Info.plist"

echo "==> Copying SwiftPM resource bundles"
shopt -s nullglob
bundles=("$BUILD_DIR"/*.bundle)
shopt -u nullglob
if [[ ${#bundles[@]} -eq 0 ]]; then
  echo "error: no SwiftPM resource bundles in $BUILD_DIR" >&2
  echo "KeyboardShortcuts requires KeyboardShortcuts_KeyboardShortcuts.bundle" >&2
  exit 1
fi
for bundle in "${bundles[@]}"; do
  name="$(basename "$bundle")"
  echo "    $name -> Contents/Resources/"
  ditto "$bundle" "$APP_DIR/Contents/Resources/$name"
done
if [[ ! -d "$APP_DIR/Contents/Resources/KeyboardShortcuts_KeyboardShortcuts.bundle" ]]; then
  echo "error: KeyboardShortcuts_KeyboardShortcuts.bundle missing from Contents/Resources" >&2
  exit 1
fi

xattr -cr "$APP_DIR" 2>/dev/null || true

if [[ -n "$SIGN_IDENTITY" ]]; then
  echo "==> Signing with: $SIGN_IDENTITY"
  codesign --force --deep --options runtime --timestamp --sign "$SIGN_IDENTITY" "$APP_DIR"
else
  echo "==> Ad-hoc signing"
  codesign --force --deep --sign - "$APP_DIR"
fi
codesign --verify --verbose "$APP_DIR"

echo "==> Creating DMG"
cd "$ROOT"
hdiutil create -volname "Clipper" -srcfolder Clipper.app -ov -format UDZO "Clipper-$VERSION.dmg"
rm -rf Clipper.app

echo "==> Done: Clipper-$VERSION.dmg"
shasum -a 256 "Clipper-$VERSION.dmg" | tee "Clipper-$VERSION.dmg.sha256"
